version: 2

sources:
  - name: local_bike
    description: Données brutes Local Bike (importées dans BigQuery)
    schema: local_bike
    tables:
      - name: brands
      - name: categories
      - name: customers
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name: stores